### ISSUE TITLE
Modify image digest comparison logic

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/warden#282]
**Description:**
We need to change [how warden handles image digest comparisons](https://github.com/kyma-project/warden/blob/d45a4133c6855e4c7f8e250e1c41538e1172de31/internal/validate/image.go#L112-L136). Currently, Warden compares the image digest from the Notary (Signify) service with the image configuration's digest. The requirement is to modify this logic to compare the image digest returned by the Notary service with the **image descriptor's digest**, not the config's digest.

To ensure backward compatibility with images that were signed using the older method (digest comparison with the config's digest), we should implement a fallback comparison mechanism: Compare the digest using the new method first (image descriptor's digest) and if that fails, execute a fallback attempt with the older method (image config's digest).

**Reason**
The sha of the whole manifest (Descriptor.digest) and its bytesize (Descriptor.size) are the standard ones used by docker and they should be used when sending signing data. The warden checksum comparison should respect that

**Acceptance Criteria:**
 - [x]   Warden should first compare the digest from the Notary (Signify) service with the image descriptor's digest.
 - [x]   If the primary comparison fails, Warden should fallback to comparing the Notary digest with the image config's digest (to support older signed images).
 - [x]  In case of fallback, log a warning message indicating that the older comparison mechanism was used.

**Testing Strategy**

Extend the unit test cases:
   - Tests should cover both scenarios: successful digest comparison using the new method and fallback to the old method.
   - Negative tests should validate that both comparisons fail when the image digests are incorrect.

This change affects Warden’s image validation process, and any issues in the logic could cause deployments of signed images to fail. Acceptance testing in a DEV environment is recommended before deployment to production.

**Additional Context:**

- The fallback mechanism ensures that warden can support both new and old image signing mechanisms without breaking existing deployments.
- A change in the build jobs should follow - after this change is delivered to all clusters, the tooling team should change the image signing mechanism.
- Last, but not least, the fallback logic can be removed from warden
 
**Hints**
In order to fetch descriptor's digest you can use the follwoving command. Keda-manager is used to illustrate:
`docker manifest inspect -v europe-docker.pkg.dev/kyma-project/prod/keda-manager:1.3.0 | jq .Descriptor.digest`

**Attachments**
https://pages.github.tools.sap/Repository-Services/Signify/how_to/manage_signatures/

**Comment by halamix2** [comment]
We should also check if the image is in fact a list of images (Index / multiplatform image) and use the correct digest (`remote.Image()` only returns data for the first image in list instead for the whole list):
- #286
