### ISSUE TITLE
Signify Operator should watch namespaces to control when to  engage or disable image verification

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/warden#32]
**Description**
we need additional control-loop that will engage/disable signature verification of image signatures for pods in a given namespace  whenever a control-label ("protected namespace marker") is introduced/removed in the namespace

**Reason**
It is needed to mitigate the situation when user removes label from protected namespace ( i.e kyma-system) and attempts to deploy an image afterwards. In theory he can deploy a malicious image in the time period until the namespace label is back.

**Comment by dbadura** [comment]
We need to add integration tests
