### ISSUE TITLE
Warden reconciliation loop causes DoS to the Notary service for unsigned images

### ISSUE THREAD

**Issue by Ressetkk** [kyma-project/warden#38]
/kind bug

Upon further inspection of Signify access logs I've managed to find a problem where Warden's reconciliation loop would cause unintended DoS attack when it asks for unsigned images.

Once every 10 minutes, for a `failed` image the retry reconciliation is issued. This currently occurs for every instance where Warden is deployed. https://github.com/kyma-project/warden/blob/b6285328efb207f8ba0d1b7fe58f9b604d61c770/controllers/pod_controller.go#L81. As some of the images that we use are not yet signed, every request for unsigned images queries Notaty server, increasing load.

Cache is not working for unsigned images, because Warden only caches signatures for already signed images.

Possible solutions:
* Cache responses from Notary
* Increase the time between retries to hours
* Remove retry logic and rely on automatic K8s reconciliation schedule (around every 10 hours).

**Comment by kwiatekus** [comment]
- Change default to 60 Min
 - expose as overridable parameter managed by SRE

**Comment by kwiatekus** [comment]
requeueAfter period is changed to 60min and is configurable per landscape
