### ISSUE TITLE
Restart operator and admission when configuration change

### ISSUE THREAD

**Issue by dbadura** [kyma-project/warden#79]
Warden is configured by files which causes that's is not reload itself on configuration change, because the deployment is not changed.
Warden should be able to load newest configuration from file when it changes.
It's very common that somebody change warden configuration but forgot to restart the pods.

Proposed solution:
In k8s kubelet update the file from configmap when the configmap is changed.

The simplest solution is to:
- catch config file change 
- shutdown gracefully to reload the configuration

**Comment by kwiatekus** [comment]
I am not sure if we really need it for runtime changes.
